// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:skyfit_pro/utils/env_config.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static FirebaseOptions get web => FirebaseOptions(
  apiKey: EnvConfig.firebaseApiKey,
  appId: EnvConfig.firebaseAppId,
  messagingSenderId: EnvConfig.firebaseMessagingSenderId,
  projectId: EnvConfig.firebaseProjectId,
  authDomain: EnvConfig.firebaseAuthDomain,
  storageBucket: EnvConfig.firebaseStorageBucket,
  measurementId: 'G-CF2W8S63YD',
);

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Rvi8rB3A8OBWdAfOVd5J5cqv3ZJs3SQ',
    appId: '1:30679119611:android:2d516bd00b6f3a4fe4e25e',
    messagingSenderId: '30679119611',
    projectId: 'skyfitpro-b293c',
    storageBucket: 'skyfitpro-b293c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApgICYElIqTK7CJFzF9htFnpV-oPTPvcg',
    appId: '1:30679119611:ios:80a9c1c3c64acfc6e4e25e',
    messagingSenderId: '30679119611',
    projectId: 'skyfitpro-b293c',
    storageBucket: 'skyfitpro-b293c.firebasestorage.app',
    iosClientId: '30679119611-me78s97enq3rq2m3b5003362m29phtuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.skyfitPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApgICYElIqTK7CJFzF9htFnpV-oPTPvcg',
    appId: '1:30679119611:ios:80a9c1c3c64acfc6e4e25e',
    messagingSenderId: '30679119611',
    projectId: 'skyfitpro-b293c',
    storageBucket: 'skyfitpro-b293c.firebasestorage.app',
    iosClientId: '30679119611-me78s97enq3rq2m3b5003362m29phtuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.skyfitPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vX3ytNOZI9SN6czTQBrCK7NVRbXw34g',
    appId: '1:30679119611:web:7b003fe6e4a05ccfe4e25e',
    messagingSenderId: '30679119611',
    projectId: 'skyfitpro-b293c',
    authDomain: 'skyfitpro-b293c.firebaseapp.com',
    storageBucket: 'skyfitpro-b293c.firebasestorage.app',
    measurementId: 'G-Z7LV3D7THN',
  );

}